/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: "ap-southeast-1",
	aws_cognito_identity_pool_id:
		"ap-southeast-1:89c75f21-668d-47b1-be86-755c2ec1deed",
	aws_cognito_region: "ap-southeast-1",
	aws_user_pools_id: "ap-southeast-1_KSVm60eTa",
	aws_user_pools_web_client_id: "aflvscnku2qn9l3rl0gsl153q",
	oauth: {
		domain:
			"femaylubakba9ba6417c-9ba6417c-dev.auth.ap-southeast-1.amazoncognito.com",
		scope: [
			"phone",
			"email",
			"openid",
			"profile",
			"aws.cognito.signin.user.admin",
		],
		redirectSignIn: "https://main.d3jogoawrzbzne.amplifyapp.com/",
		redirectSignOut: "https://main.d3jogoawrzbzne.amplifyapp.com/",
		responseType: "code",
	},
	federationTarget: "COGNITO_USER_POOLS",
	aws_cognito_username_attributes: ["EMAIL"],
	aws_cognito_social_providers: ["GOOGLE"],
	aws_cognito_signup_attributes: ["EMAIL"],
	aws_cognito_mfa_configuration: "OFF",
	aws_cognito_mfa_types: ["SMS"],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: [],
	},
	aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
